
title: Xuesong LI

description: Technology makes the world a better place!

author: Xuesong Li

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md

# theme: jekyll-theme-tactile
theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
