
title: Xuesong (Benjamin) Li

description: personnel page

author: Xuesong Li

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md

# theme: jekyll-theme-tactile
theme: jekyll-theme-midnight
